INSERT INTO departamento(nombre, acronimo) VALUES('Ingeniería de Sistemas Telemáticos', 'DIT');
INSERT INTO departamento(nombre, acronimo) VALUES('Señales, Sistemas y Radiocomunicaciones', 'SSR');
INSERT INTO departamento(nombre, acronimo) VALUES('Tecnología Fotónica y Bioingeniería', 'TFB');
INSERT INTO departamento(nombre, acronimo) VALUES('Matemática Aplicada a las Tecnologías de la Información y las Comunicaciones', 'MAT');
INSERT INTO departamento(nombre, acronimo) VALUES('Ingeniería Electrónica', 'DIE');
INSERT INTO departamento(nombre, acronimo) VALUES('Electrónica Física', 'IES');

INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Alejandro Alonso Muñoz', '123456', 'B319', 'aalonso@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Gregorio Fernández Fernández', '12346', 'B208', 'gfer@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Encarna Pastor', '12347', 'B218', 'encarna@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Juan Antonio de la Puente', '12348', 'B318', 'jpuente@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Juan Quemada Vives ', '12349', 'B202', 'jquemada@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Monica Cortés Sack', '12350', 'B202', 'cortesm@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('David Fernández Cambronero', '12351', 'B216', 'david@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('José Carlos González', '12352', 'C212', 'jgonzalez@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Gabriel Huecas Fernández-Toribio', '12353', 'B212', 'gabriel@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Carlos Ángel Iglesias', '12354', 'C211', 'cif@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Miguel Ángel de Miguel', '12355', 'B323', 'mmiguel@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Santiago Pavón Gómez', '12356', 'B212', 'santiago@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Tomás Robles Valladares', '12357', 'B213', 'robles@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Joaquín Salvachúa', '12358', 'C219', 'jsalvachua@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Víctor Abraham Villagrá', '12359', 'B217', 'villagra@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Angel Alvarez-Rodriguez', '12360', 'C218', 'aalvarez@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Juan Carlos Yelmo', '12361', 'C217', 'jcyelmo@dit.upm.es', 1);
INSERT INTO profesor(nombre, NRP, despacho, email, id_departamento) VALUES('Jose Maria Del Alamo', '12362', 'C218', 'jmdela@dit.upm.es', 1);



INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(1, 1, 'FTEL', 'Fundamentos de los Sistemas Telemáticos', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(1, 2, 'PROG', 'Programación', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(2, 1, 'TEWC', 'Tecnologías Web de Cliente', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(2, 2, 'RSTC', 'Redes y Servicios de Telecomunicación', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(2, 2, 'ADSW', 'Análisis y Diseño de Software', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(3, 1, 'TINF', 'Teoría de la Información', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(3, 1, 'RDOR', 'Redes de Ordenadores', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(3, 2, 'CORE', 'Computación en Red', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 1, 'RECO', 'Redes Corporativas', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 1, 'SEGU', 'Seguridad en Sistemas y Redes de Telecomunicación', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 1, 'RCMO', 'Redes de Comunicaciones Móviles', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 1, 'IWEB', 'Ingeniería Web', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 1, 'CDPS', 'Centros de Datos y Provisión de Servicios', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 2, 'DORE', 'Dimensionado y Operación de Redes', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 2, 'ISST', 'Ingeniería de Sistemas y Servicios Telemáticos', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 2, 'RSDR', 'Redes y servicios de radio', 1);
INSERT INTO asignatura(curso, semestre, acronimo, nombre, id_departamento) VALUES(4, 2, 'TFG', 'Trabajo Fin de Grado', 1);

INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(1, 3);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(1, 4);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(1, 5);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 1);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 6);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 10);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 11);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 12);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(2, 16);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(3, 9);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(5, 1);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(5, 4);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(5, 8);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(5, 9);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(5, 15);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(6, 8);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(6, 14);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(7, 7);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(8, 5);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(8, 11);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(8, 13);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(8, 17);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(8, 18);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(10, 14);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(12, 8);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(12, 11);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(12, 13);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(13, 1);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(13, 7);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(13, 13);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(15, 16);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(15, 17);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(15, 18);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 1);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 2);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 3);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 4);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 5);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 6);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 7);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 8);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 9);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 10);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 11);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 12);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 13);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 14);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 15);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 16);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 17);
INSERT INTO profesor_imparte_asignatura(id_asignatura, id_profesor) VALUES(17, 18);